receivers:
  castai_audit_logs_v2:
    api:
      url: ${env:CASTAI_API_URL}
      key: ${env:CASTAI_API_KEY}
    poll_interval: 10s
    page_limit: 100
    checkpoint_file: ./audit_logs_v2_checkpoint.json
    filters:
      domains: [autoscaler, workload]
      resources: [node]
      actions: [deleted]

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [castai_audit_logs_v2]
      exporters: [debug]
