dist:
  name: castai-collector
  description: CAST AI OTel Collector that outputs Audit Logs to the console
  output_path: ./castai-collector

receivers:
  - gomod: github.com/castai/audit-logs-receiver/audit-logs v0.147.0
    import: github.com/castai/audit-logs-receiver/audit-logs
    name: "auditlogsreceiver"
    path: "./auditlogsreceiver/"
  - gomod: github.com/castai/audit-logs-receiver/audit-logs/v2 v2.0.0
    import: github.com/castai/audit-logs-receiver/audit-logs/v2
    name: "auditlogsreceiver"
    path: "./auditlogsreceiver/v2/"

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.147.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.147.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.147.0


exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.147.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/coralogixexporter v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.147.0

