auth_enabled: false # disable multi-tenancy

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  max_cache_freshness_per_query: 10m
  allow_structured_metadata: true
  reject_old_samples: false
  reject_old_samples_max_age: 8760h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  split_queries_by_interval: 15m # parallelize queries in 15min intervals
  unordered_writes: true
  max_query_length: 5000h
  otlp_config:
    resource_attributes:
      attributes_config:
        - action: index_label
          attributes:
            - service_name

ingester:
  chunk_idle_period: 5m
  chunk_target_size: 1048576
  max_chunk_age: 8760h  # 1y
  wal:
    enabled: true

ruler:
  alertmanager_url: http://localhost:9093
