auth_enabled: false # disable multi-tenancy

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: false
  reject_old_samples_max_age: 8760h # 1y
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  split_queries_by_interval: 15m # parallelize queries in 15min intervals
  unordered_writes: true
  max_query_length: 5000h # Default: 721h

chunk_store_config:
  max_look_back_period: 8760h # 1y

ingester:
  max_chunk_age: 43800h # 5y

ruler:
  alertmanager_url: http://localhost:9093
