// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("castai_audit_logs_v2")
	ScopeName = "github.com/castai/audit-logs-receiver/audit-logs/v2"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
