receivers:
  castai_audit_logs:
    api:
      url:             ${env:CASTAI_API_URL} # Use CASTAI_API_URL env variable to override default API URL (https://api.cast.ai/)
      key:             ${env:CASTAI_API_KEY} # Use CASTAI_API_KEY env variable to provide API Access Key
    poll_interval_sec: 10 # This parameter defines poll cycle in seconds.
    page_limit:        100 # This parameter defines the max number of records returned from the backend in one page.
    storage:
      type: "persistent"
      filename: "/var/lib/otelcol/file_storage/audit_logs_poll_data.json"

exporters:
  coralogix:
    # The Coralogix domain
    domain: "coralogix.com"
    # Your Coralogix private key is sensitive
    private_key: "xxx"

    # (Optional) Ordered list of Resource attributes that are used for Coralogix
    # AppName and SubSystem values. The first non-empty Resource attribute is used.
    # Example: application_name_attributes: ["k8s.namespace.name", "service.namespace"]
    # Example: subsystem_name_attributes: ["k8s.deployment.name", "k8s.daemonset.name", "service.name"]
    # application_name_attributes:
    # - "service.namespace"
    # subsystem_name_attributes:
    # - "service.name"

    # Traces, Metrics and Logs emitted by this OpenTelemetry exporter 
    # are tagged in Coralogix with the default application and subsystem constants.
    application_name: "MyBusinessEnvironment"
    subsystem_name: "MyBusinessSystem"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [castai_audit_logs]
      exporters: [coralogix]
