// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("castai_audit_logs")
)

const (
	LogsStability = component.StabilityLevelAlpha
)
