// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

const (
	Type          = "castai-audit-logs"
	LogsStability = component.StabilityLevelAlpha
)
