apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castai-otel-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-otel-collector.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-otel-collector.annotations" . | nindent 4 }}
  {{- end }}
data:
  config: |
  {{- toYaml .Values.config | nindent 4 }}